In [1]:
import sys

sys.path.append("../src")

In [2]:
from experiments.multimodal_experiment import *
from utils import *

# Multimodal
EEG + EYE + OpenFace

In [3]:
run_experiment(dataset_root="../../Dataset/");

Running Experiment on Fold 0
Participant 407 is missing at least one modality (EYE)

  0%|          | 0/24 [00:00<?, ?it/s]

  0%|          | 0/521 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/113 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/125 [00:00<?, ?it/s]

/home/ammar/MultimodalEngagement/notebooks/../src/models/multimodal_fusion.py:67: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  criterion = nn.BCEWithLogitsLoss(pos_weight=torch.tensor(pos_weight).to(device))

Epochs:   0%|          | 0/100 [00:00<?, ?it/s]

Epoch 1/100:
Train Loss: 0.3807, Train Acc: 0.4395
Val Loss: 0.3719, Val Acc: 0.3274
New best model saved!
Epoch 2/100:
Train Loss: 0.3684, Train Acc: 0.6583
Val Loss: 0.3762, Val Acc: 0.6991
Epoch 3/100:
Train Loss: 0.3624, Train Acc: 0.5547
Val Loss: 0.3796, Val Acc: 0.3540
Epoch 4/100:
Train Loss: 0.3364, Train Acc: 0.3935
Val Loss: 0.3602, Val Acc: 0.4248
New best model saved!
Epoch 5/100:
Train Loss: 0.3286, Train Acc: 0.6084
Val Loss: 0.3734, Val Acc: 0.6991
Epoch 6/100:
Train Loss: 0.3348, Train Acc: 0.7044
Val Loss: 0.3717, Val Acc: 0.6991
Epoch 7/100:
Train Loss: 0.3612, Train Acc: 0.6718
Val Loss: 0.3610, Val Acc: 0.6549
Epoch 8/100:
Train Loss: 0.3413, Train Acc: 0.4914
Val Loss: 0.3638, Val Acc: 0.3894
Epoch 9/100:
Train Loss: 0.3495, Train Acc: 0.3992
Val Loss: 0.3492, Val Acc: 0.4779
New best model saved!
Epoch 10/100:
Train Loss: 0.3795, Train Acc: 0.6123
Val Loss: 0.3507, Val Acc: 0.6460
Epoch 11/100:
Train Loss: 0.3494, Train Acc: 0.4472
Val Loss: 0.3819, Val Acc: 0.3717
Epoch 12/100:
Train Loss: 0.3536, Train Acc: 0.4242
Val Loss: 0.3493, Val Acc: 0.5575
Epoch 13/100:
Train Loss: 0.3361, Train Acc: 0.5969
Val Loss: 0.3483, Val Acc: 0.5929
New best model saved!
Epoch 14/100:
Train Loss: 0.3341, Train Acc: 0.6276
Val Loss: 0.3468, Val Acc: 0.6018
New best model saved!
Epoch 15/100:
Train Loss: 0.3151, Train Acc: 0.6507
Val Loss: 0.3418, Val Acc: 0.6372
New best model saved!
Epoch 16/100:
Train Loss: 0.3494, Train Acc: 0.6987
Val Loss: 0.3456, Val Acc: 0.6991
Epoch 17/100:
Train Loss: 0.3173, Train Acc: 0.6641
Val Loss: 0.3329, Val Acc: 0.5929
New best model saved!
Epoch 18/100:
Train Loss: 0.3425, Train Acc: 0.6161
Val Loss: 0.3329, Val Acc: 0.6195
New best model saved!
Epoch 19/100:
Train Loss: 0.3491, Train Acc: 0.4319
Val Loss: 0.3499, Val Acc: 0.4425
Epoch 20/100:
Train Loss: 0.3376, Train Acc: 0.5106
Val Loss: 0.3373, Val Acc: 0.5841
Epoch 21/100:
Train Loss: 0.3190, Train Acc: 0.6449
Val Loss: 0.3345, Val Acc: 0.6283
Epoch 22/100:
Train Loss: 0.3327, Train Acc: 0.7006
Val Loss: 0.3341, Val Acc: 0.6106
Epoch 23/100:
Train Loss: 0.3307, Train Acc: 0.5566
Val Loss: 0.3398, Val Acc: 0.4425
Epoch 24/100:
Train Loss: 0.3199, Train Acc: 0.5547
Val Loss: 0.3336, Val Acc: 0.6195
Epoch 25/100:
Train Loss: 0.3207, Train Acc: 0.7083
Val Loss: 0.3440, Val Acc: 0.6637
Epoch 26/100:
Train Loss: 0.3190, Train Acc: 0.6891
Val Loss: 0.3410, Val Acc: 0.6018
Epoch 27/100:
Train Loss: 0.3185, Train Acc: 0.7006
Val Loss: 0.3430, Val Acc: 0.6018
Epoch 28/100:
Train Loss: 0.3211, Train Acc: 0.6852
Val Loss: 0.3423, Val Acc: 0.5752
Early stopping triggered after 28 epochs!
Loaded best model from ../results/models/0.pth
Running Experiment on Fold 1

  0%|          | 0/25 [00:00<?, ?it/s]

  0%|          | 0/593 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/74 [00:00<?, ?it/s]

Participant 407 is missing at least one modality (EYE)

  0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/92 [00:00<?, ?it/s]

/home/ammar/MultimodalEngagement/notebooks/../src/models/multimodal_fusion.py:67: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  criterion = nn.BCEWithLogitsLoss(pos_weight=torch.tensor(pos_weight).to(device))

Epochs:   0%|          | 0/100 [00:00<?, ?it/s]

Epoch 1/100:
Train Loss: 0.4266, Train Acc: 0.3575
Val Loss: 0.3752, Val Acc: 0.2297
New best model saved!
Epoch 2/100:
Train Loss: 0.3781, Train Acc: 0.5481
Val Loss: 0.3773, Val Acc: 0.6351
Epoch 3/100:
Train Loss: 0.3682, Train Acc: 0.6627
Val Loss: 0.3801, Val Acc: 0.4730
Epoch 4/100:
Train Loss: 0.3938, Train Acc: 0.5649
Val Loss: 0.3786, Val Acc: 0.3108
Epoch 5/100:
Train Loss: 0.3795, Train Acc: 0.5025
Val Loss: 0.3805, Val Acc: 0.4189
Epoch 6/100:
Train Loss: 0.3812, Train Acc: 0.6206
Val Loss: 0.3766, Val Acc: 0.3108
Epoch 7/100:
Train Loss: 0.3740, Train Acc: 0.6273
Val Loss: 0.3778, Val Acc: 0.5135
Epoch 8/100:
Train Loss: 0.3696, Train Acc: 0.6307
Val Loss: 0.3827, Val Acc: 0.7432
Epoch 9/100:
Train Loss: 0.3742, Train Acc: 0.7032
Val Loss: 0.3772, Val Acc: 0.6892
Epoch 10/100:
Train Loss: 0.3697, Train Acc: 0.6223
Val Loss: 0.3739, Val Acc: 0.3649
New best model saved!
Epoch 11/100:
Train Loss: 0.3618, Train Acc: 0.5295
Val Loss: 0.3803, Val Acc: 0.4054
Epoch 12/100:
Train Loss: 0.3680, Train Acc: 0.6847
Val Loss: 0.4000, Val Acc: 0.7838
Epoch 13/100:
Train Loss: 0.3643, Train Acc: 0.6341
Val Loss: 0.3738, Val Acc: 0.3243
New best model saved!
Epoch 14/100:
Train Loss: 0.3706, Train Acc: 0.6054
Val Loss: 0.3805, Val Acc: 0.6216
Epoch 15/100:
Train Loss: 0.3678, Train Acc: 0.6037
Val Loss: 0.3666, Val Acc: 0.3514
New best model saved!
Epoch 16/100:
Train Loss: 0.3781, Train Acc: 0.5599
Val Loss: 0.3703, Val Acc: 0.4054
Epoch 17/100:
Train Loss: 0.3632, Train Acc: 0.4823
Val Loss: 0.3664, Val Acc: 0.3243
New best model saved!
Epoch 18/100:
Train Loss: 0.3720, Train Acc: 0.6492
Val Loss: 0.3881, Val Acc: 0.7297
Epoch 19/100:
Train Loss: 0.3655, Train Acc: 0.5750
Val Loss: 0.3628, Val Acc: 0.3378
New best model saved!
Epoch 20/100:
Train Loss: 0.3580, Train Acc: 0.6290
Val Loss: 0.4028, Val Acc: 0.7703
Epoch 21/100:
Train Loss: 0.3527, Train Acc: 0.7403
Val Loss: 0.3782, Val Acc: 0.5405
Epoch 22/100:
Train Loss: 0.3507, Train Acc: 0.6290
Val Loss: 0.3706, Val Acc: 0.5135
Epoch 23/100:
Train Loss: 0.3637, Train Acc: 0.7049
Val Loss: 0.3735, Val Acc: 0.4459
Epoch 24/100:
Train Loss: 0.3492, Train Acc: 0.5245
Val Loss: 0.3711, Val Acc: 0.3649
Epoch 25/100:
Train Loss: 0.3582, Train Acc: 0.6914
Val Loss: 0.3762, Val Acc: 0.4459
Epoch 26/100:
Train Loss: 0.3561, Train Acc: 0.5447
Val Loss: 0.3794, Val Acc: 0.4189
Epoch 27/100:
Train Loss: 0.3506, Train Acc: 0.6863
Val Loss: 0.4007, Val Acc: 0.5946
Epoch 28/100:
Train Loss: 0.3484, Train Acc: 0.6728
Val Loss: 0.3815, Val Acc: 0.4595
Epoch 29/100:
Train Loss: 0.3575, Train Acc: 0.6965
Val Loss: 0.3920, Val Acc: 0.6351
Early stopping triggered after 29 epochs!
Loaded best model from ../results/models/1.pth
Running Experiment on Fold 2
Participant 407 is missing at least one modality (EYE)

  0%|          | 0/23 [00:00<?, ?it/s]

  0%|          | 0/501 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/103 [00:00<?, ?it/s]

  0%|          | 0/6 [00:00<?, ?it/s]

  0%|          | 0/155 [00:00<?, ?it/s]

/home/ammar/MultimodalEngagement/notebooks/../src/models/multimodal_fusion.py:67: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  criterion = nn.BCEWithLogitsLoss(pos_weight=torch.tensor(pos_weight).to(device))

Epochs:   0%|          | 0/100 [00:00<?, ?it/s]

Epoch 1/100:
Train Loss: 0.4136, Train Acc: 0.6287
Val Loss: 0.3534, Val Acc: 0.5049
New best model saved!
Epoch 2/100:
Train Loss: 0.3731, Train Acc: 0.4830
Val Loss: 0.3482, Val Acc: 0.7282
New best model saved!
Epoch 3/100:
Train Loss: 0.3685, Train Acc: 0.6108
Val Loss: 0.3519, Val Acc: 0.5825
Epoch 4/100:
Train Loss: 0.3651, Train Acc: 0.6527
Val Loss: 0.3474, Val Acc: 0.7864
New best model saved!
Epoch 5/100:
Train Loss: 0.3659, Train Acc: 0.5888
Val Loss: 0.3652, Val Acc: 0.4660
Epoch 6/100:
Train Loss: 0.3626, Train Acc: 0.6327
Val Loss: 0.3518, Val Acc: 0.7864
Epoch 7/100:
Train Loss: 0.3553, Train Acc: 0.7066
Val Loss: 0.3532, Val Acc: 0.7670
Epoch 8/100:
Train Loss: 0.3652, Train Acc: 0.6287
Val Loss: 0.3586, Val Acc: 0.6214
Epoch 9/100:
Train Loss: 0.3644, Train Acc: 0.6507
Val Loss: 0.3516, Val Acc: 0.7476
Epoch 10/100:
Train Loss: 0.3591, Train Acc: 0.6547
Val Loss: 0.3546, Val Acc: 0.6893
Epoch 11/100:
Train Loss: 0.3505, Train Acc: 0.6846
Val Loss: 0.3544, Val Acc: 0.7476
Epoch 12/100:
Train Loss: 0.3464, Train Acc: 0.7285
Val Loss: 0.3547, Val Acc: 0.7573
Epoch 13/100:
Train Loss: 0.3470, Train Acc: 0.6607
Val Loss: 0.3576, Val Acc: 0.7184
Epoch 14/100:
Train Loss: 0.3401, Train Acc: 0.7166
Val Loss: 0.3647, Val Acc: 0.7573
Early stopping triggered after 14 epochs!
Loaded best model from ../results/models/2.pth
Running Experiment on Fold 3
Participant 407 is missing at least one modality (EYE)

/home/ammar/miniconda3/envs/torch/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/ammar/miniconda3/envs/torch/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/ammar/miniconda3/envs/torch/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

  0%|          | 0/23 [00:00<?, ?it/s]

  0%|          | 0/521 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/104 [00:00<?, ?it/s]

  0%|          | 0/6 [00:00<?, ?it/s]

  0%|          | 0/134 [00:00<?, ?it/s]

/home/ammar/MultimodalEngagement/notebooks/../src/models/multimodal_fusion.py:67: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  criterion = nn.BCEWithLogitsLoss(pos_weight=torch.tensor(pos_weight).to(device))

Epochs:   0%|          | 0/100 [00:00<?, ?it/s]

Epoch 1/100:
Train Loss: 0.4192, Train Acc: 0.4511
Val Loss: 0.4547, Val Acc: 0.1731
New best model saved!
Epoch 2/100:
Train Loss: 0.3762, Train Acc: 0.5221
Val Loss: 0.3524, Val Acc: 0.8269
New best model saved!
Epoch 3/100:
Train Loss: 0.3970, Train Acc: 0.6526
Val Loss: 0.3914, Val Acc: 0.2788
Epoch 4/100:
Train Loss: 0.3848, Train Acc: 0.3570
Val Loss: 0.3850, Val Acc: 0.2885
Epoch 5/100:
Train Loss: 0.3748, Train Acc: 0.5278
Val Loss: 0.3536, Val Acc: 0.4904
Epoch 6/100:
Train Loss: 0.3680, Train Acc: 0.4683
Val Loss: 0.3891, Val Acc: 0.2788
Epoch 7/100:
Train Loss: 0.3614, Train Acc: 0.5144
Val Loss: 0.3497, Val Acc: 0.4904
New best model saved!
Epoch 8/100:
Train Loss: 0.3579, Train Acc: 0.6507
Val Loss: 0.3329, Val Acc: 0.8269
New best model saved!
Epoch 9/100:
Train Loss: 0.3954, Train Acc: 0.6622
Val Loss: 0.3557, Val Acc: 0.3173
Epoch 10/100:
Train Loss: 0.3875, Train Acc: 0.3474
Val Loss: 0.4837, Val Acc: 0.1827
Epoch 11/100:
Train Loss: 0.3711, Train Acc: 0.4280
Val Loss: 0.3402, Val Acc: 0.5096
Epoch 12/100:
Train Loss: 0.3538, Train Acc: 0.5950
Val Loss: 0.3430, Val Acc: 0.5096
Epoch 13/100:
Train Loss: 0.3748, Train Acc: 0.6200
Val Loss: 0.3704, Val Acc: 0.3077
Epoch 14/100:
Train Loss: 0.3787, Train Acc: 0.3935
Val Loss: 0.4279, Val Acc: 0.2404
Epoch 15/100:
Train Loss: 0.3608, Train Acc: 0.4971
Val Loss: 0.3334, Val Acc: 0.6635
Epoch 16/100:
Train Loss: 0.4394, Train Acc: 0.6871
Val Loss: 0.3297, Val Acc: 0.7404
New best model saved!
Epoch 17/100:
Train Loss: 0.3752, Train Acc: 0.5067
Val Loss: 0.3996, Val Acc: 0.2404
Epoch 18/100:
Train Loss: 0.3607, Train Acc: 0.4798
Val Loss: 0.3257, Val Acc: 0.6827
New best model saved!
Epoch 19/100:
Train Loss: 0.3584, Train Acc: 0.6699
Val Loss: 0.3284, Val Acc: 0.6154
Epoch 20/100:
Train Loss: 0.3452, Train Acc: 0.6334
Val Loss: 0.3339, Val Acc: 0.5673
Epoch 21/100:
Train Loss: 0.3741, Train Acc: 0.6411
Val Loss: 0.3339, Val Acc: 0.5481
Epoch 22/100:
Train Loss: 0.3706, Train Acc: 0.6180
Val Loss: 0.3370, Val Acc: 0.4231
Epoch 23/100:
Train Loss: 0.3652, Train Acc: 0.4779
Val Loss: 0.3699, Val Acc: 0.2788
Epoch 24/100:
Train Loss: 0.3595, Train Acc: 0.4914
Val Loss: 0.3428, Val Acc: 0.3173
Epoch 25/100:
Train Loss: 0.3590, Train Acc: 0.5873
Val Loss: 0.3436, Val Acc: 0.4231
Epoch 26/100:
Train Loss: 0.3451, Train Acc: 0.6142
Val Loss: 0.3488, Val Acc: 0.4135
Epoch 27/100:
Train Loss: 0.3716, Train Acc: 0.6257
Val Loss: 0.3568, Val Acc: 0.3654
Epoch 28/100:
Train Loss: 0.3502, Train Acc: 0.5278
Val Loss: 0.3708, Val Acc: 0.2885
Early stopping triggered after 28 epochs!
Loaded best model from ../results/models/3.pth
Running Experiment on Fold 4
Participant 407 is missing at least one modality (EYE)

  0%|          | 0/24 [00:00<?, ?it/s]

  0%|          | 0/561 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/91 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/107 [00:00<?, ?it/s]

/home/ammar/MultimodalEngagement/notebooks/../src/models/multimodal_fusion.py:67: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  criterion = nn.BCEWithLogitsLoss(pos_weight=torch.tensor(pos_weight).to(device))

Epochs:   0%|          | 0/100 [00:00<?, ?it/s]

Epoch 1/100:
Train Loss: 0.4063, Train Acc: 0.6435
Val Loss: 0.3706, Val Acc: 0.7473
New best model saved!
Epoch 2/100:
Train Loss: 0.4141, Train Acc: 0.4617
Val Loss: 0.3684, Val Acc: 0.7802
New best model saved!
Epoch 3/100:
Train Loss: 0.4017, Train Acc: 0.5508
Val Loss: 0.3687, Val Acc: 0.6923
Epoch 4/100:
Train Loss: 0.3987, Train Acc: 0.5811
Val Loss: 0.3653, Val Acc: 0.7802
New best model saved!
Epoch 5/100:
Train Loss: 0.3993, Train Acc: 0.6114
Val Loss: 0.3633, Val Acc: 0.7253
New best model saved!
Epoch 6/100:
Train Loss: 0.4051, Train Acc: 0.6524
Val Loss: 0.3611, Val Acc: 0.7253
New best model saved!
Epoch 7/100:
Train Loss: 0.4016, Train Acc: 0.5383
Val Loss: 0.3594, Val Acc: 0.7582
New best model saved!
Epoch 8/100:
Train Loss: 0.3884, Train Acc: 0.6096
Val Loss: 0.3601, Val Acc: 0.7143
Epoch 9/100:
Train Loss: 0.3846, Train Acc: 0.6310
Val Loss: 0.3600, Val Acc: 0.7692
Epoch 10/100:
Train Loss: 0.3858, Train Acc: 0.6114
Val Loss: 0.3567, Val Acc: 0.7802
New best model saved!
Epoch 11/100:
Train Loss: 0.3857, Train Acc: 0.6863
Val Loss: 0.3590, Val Acc: 0.7802
Epoch 12/100:
Train Loss: 0.3845, Train Acc: 0.6185
Val Loss: 0.3549, Val Acc: 0.7363
New best model saved!
Epoch 13/100:
Train Loss: 0.3831, Train Acc: 0.6542
Val Loss: 0.3562, Val Acc: 0.7802
Epoch 14/100:
Train Loss: 0.3758, Train Acc: 0.6453
Val Loss: 0.3609, Val Acc: 0.4725
Epoch 15/100:
Train Loss: 0.3834, Train Acc: 0.5045
Val Loss: 0.3565, Val Acc: 0.7912
Epoch 16/100:
Train Loss: 0.3770, Train Acc: 0.7344
Val Loss: 0.3645, Val Acc: 0.7692
Epoch 17/100:
Train Loss: 0.3781, Train Acc: 0.5989
Val Loss: 0.3621, Val Acc: 0.5714
Epoch 18/100:
Train Loss: 0.3690, Train Acc: 0.6667
Val Loss: 0.3728, Val Acc: 0.7802
Epoch 19/100:
Train Loss: 0.3741, Train Acc: 0.6542
Val Loss: 0.3655, Val Acc: 0.5714
Epoch 20/100:
Train Loss: 0.3678, Train Acc: 0.6720
Val Loss: 0.3802, Val Acc: 0.8022
Epoch 21/100:
Train Loss: 0.3646, Train Acc: 0.7130
Val Loss: 0.3680, Val Acc: 0.6154
Epoch 22/100:
Train Loss: 0.3632, Train Acc: 0.6221
Val Loss: 0.3741, Val Acc: 0.7363
Early stopping triggered after 22 epochs!
Loaded best model from ../results/models/4.pth
Running Experiment on Fold 5
Participant 407 is missing at least one modality (EYE)

  0%|          | 0/23 [00:00<?, ?it/s]

  0%|          | 0/517 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/96 [00:00<?, ?it/s]

  0%|          | 0/6 [00:00<?, ?it/s]

  0%|          | 0/146 [00:00<?, ?it/s]

/home/ammar/MultimodalEngagement/notebooks/../src/models/multimodal_fusion.py:67: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  criterion = nn.BCEWithLogitsLoss(pos_weight=torch.tensor(pos_weight).to(device))

Epochs:   0%|          | 0/100 [00:00<?, ?it/s]

Epoch 1/100:
Train Loss: 0.5501, Train Acc: 0.5474
Val Loss: 0.3678, Val Acc: 0.7292
New best model saved!
Epoch 2/100:
Train Loss: 0.3985, Train Acc: 0.4952
Val Loss: 0.4026, Val Acc: 0.3333
Epoch 3/100:
Train Loss: 0.4394, Train Acc: 0.4449
Val Loss: 0.3665, Val Acc: 0.7292
New best model saved!
Epoch 4/100:
Train Loss: 0.4406, Train Acc: 0.6015
Val Loss: 0.3713, Val Acc: 0.7812
Epoch 5/100:
Train Loss: 0.4420, Train Acc: 0.3791
Val Loss: 0.3919, Val Acc: 0.3750
Epoch 6/100:
Train Loss: 0.4127, Train Acc: 0.5706
Val Loss: 0.3780, Val Acc: 0.7292
Epoch 7/100:
Train Loss: 0.4465, Train Acc: 0.6770
Val Loss: 0.3674, Val Acc: 0.7396
Epoch 8/100:
Train Loss: 0.4025, Train Acc: 0.4720
Val Loss: 0.3800, Val Acc: 0.4479
Epoch 9/100:
Train Loss: 0.4204, Train Acc: 0.5029
Val Loss: 0.3673, Val Acc: 0.7396
Epoch 10/100:
Train Loss: 0.4032, Train Acc: 0.6054
Val Loss: 0.3708, Val Acc: 0.7396
Epoch 11/100:
Train Loss: 0.3897, Train Acc: 0.5919
Val Loss: 0.3725, Val Acc: 0.7292
Epoch 12/100:
Train Loss: 0.3890, Train Acc: 0.6170
Val Loss: 0.3700, Val Acc: 0.7396
Epoch 13/100:
Train Loss: 0.4170, Train Acc: 0.6209
Val Loss: 0.3695, Val Acc: 0.7396
Early stopping triggered after 13 epochs!
Loaded best model from ../results/models/5.pth
Running Experiment on Fold 6
Participant 407 is missing at least one modality (EYE)

  0%|          | 0/29 [00:00<?, ?it/s]

  0%|          | 0/676 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/83 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/114 [00:00<?, ?it/s]

/home/ammar/MultimodalEngagement/notebooks/../src/models/multimodal_fusion.py:67: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  criterion = nn.BCEWithLogitsLoss(pos_weight=torch.tensor(pos_weight).to(device))

Epochs:   0%|          | 0/100 [00:00<?, ?it/s]

Epoch 1/100:
Train Loss: 0.3817, Train Acc: 0.5636
Val Loss: 0.4521, Val Acc: 0.6747
New best model saved!
Epoch 2/100:
Train Loss: 0.3622, Train Acc: 0.5651
Val Loss: 0.4400, Val Acc: 0.5783
New best model saved!
Epoch 3/100:
Train Loss: 0.3631, Train Acc: 0.5651
Val Loss: 0.4345, Val Acc: 0.4699
New best model saved!
Epoch 4/100:
Train Loss: 0.3598, Train Acc: 0.5429
Val Loss: 0.4590, Val Acc: 0.6627
Epoch 5/100:
Train Loss: 0.3477, Train Acc: 0.6834
Val Loss: 0.4245, Val Acc: 0.4578
New best model saved!
Epoch 6/100:
Train Loss: 0.3515, Train Acc: 0.5666
Val Loss: 0.4342, Val Acc: 0.6024
Epoch 7/100:
Train Loss: 0.3544, Train Acc: 0.5651
Val Loss: 0.4293, Val Acc: 0.5422
Epoch 8/100:
Train Loss: 0.3495, Train Acc: 0.6612
Val Loss: 0.4237, Val Acc: 0.4940
New best model saved!
Epoch 9/100:
Train Loss: 0.3502, Train Acc: 0.5607
Val Loss: 0.4721, Val Acc: 0.6506
Epoch 10/100:
Train Loss: 0.3511, Train Acc: 0.5947
Val Loss: 0.4192, Val Acc: 0.4819
New best model saved!
Epoch 11/100:
Train Loss: 0.3534, Train Acc: 0.7101
Val Loss: 0.4068, Val Acc: 0.4096
New best model saved!
Epoch 12/100:
Train Loss: 0.3461, Train Acc: 0.4630
Val Loss: 0.4553, Val Acc: 0.6386
Epoch 13/100:
Train Loss: 0.3448, Train Acc: 0.7396
Val Loss: 0.4738, Val Acc: 0.6506
Epoch 14/100:
Train Loss: 0.3412, Train Acc: 0.6109
Val Loss: 0.4493, Val Acc: 0.6386
Epoch 15/100:
Train Loss: 0.3316, Train Acc: 0.6494
Val Loss: 0.4568, Val Acc: 0.6265
Epoch 16/100:
Train Loss: 0.3413, Train Acc: 0.6524
Val Loss: 0.4649, Val Acc: 0.6386
Epoch 17/100:
Train Loss: 0.3332, Train Acc: 0.6893
Val Loss: 0.4990, Val Acc: 0.6265
Epoch 18/100:
Train Loss: 0.3328, Train Acc: 0.6760
Val Loss: 0.4134, Val Acc: 0.4819
Epoch 19/100:
Train Loss: 0.3314, Train Acc: 0.6953
Val Loss: 0.4818, Val Acc: 0.6506
Epoch 20/100:
Train Loss: 0.3377, Train Acc: 0.5459
Val Loss: 0.4986, Val Acc: 0.6506
Epoch 21/100:
Train Loss: 0.3252, Train Acc: 0.7456
Val Loss: 0.4341, Val Acc: 0.5422
Early stopping triggered after 21 epochs!
Loaded best model from ../results/models/6.pth

In [4]:
read_reports("../results/tables/eeg_eye_openface/")

Accuracy: 0.6084334195261821 ± 0.09492814523402704
ROC-AUC: 0.5182081426220945 ± 0.10994177206360137

                     Low           High            Avg.
Metric
precision     0.28 ± 0.2    0.73 ± 0.08     0.51 ± 0.11
recall       0.36 ± 0.24    0.69 ± 0.19     0.53 ± 0.09
f1-score     0.31 ± 0.22     0.7 ± 0.11      0.51 ± 0.1
support    36.14 ± 11.95  88.57 ± 20.45  124.71 ± 22.19

# Eye only

In [3]:
run_experiment(dataset_root="../../Dataset/", modalities=["EYE"], learning_rate=1e-5, exp_kwargs={"model_kwargs":{"dropout":0.5, "hidden_dim":64}});

Running Experiment on Fold 0
Participant 407 is missing at least one modality (EYE)

  0%|          | 0/24 [00:00<?, ?it/s]

  0%|          | 0/521 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/113 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/125 [00:00<?, ?it/s]

/home/ammar/MultimodalEngagement/Modeling/notebooks/../src/models/multimodal_fusion.py:73: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  criterion = nn.BCEWithLogitsLoss(pos_weight=torch.tensor(pos_weight).to(device))

Epochs:   0%|          | 0/100 [00:00<?, ?it/s]

Epoch 1/100:
Train Loss: 0.3380, Train Acc: 0.7466
Val Loss: 0.3976, Val Acc: 0.6991
New best model saved!
Epoch 2/100:
Train Loss: 0.3381, Train Acc: 0.7409
Val Loss: 0.3956, Val Acc: 0.6991
New best model saved!
Epoch 3/100:
Train Loss: 0.3346, Train Acc: 0.7370
Val Loss: 0.3934, Val Acc: 0.6991
New best model saved!
Epoch 4/100:
Train Loss: 0.3543, Train Acc: 0.7601
Val Loss: 0.3921, Val Acc: 0.6991
New best model saved!
Epoch 5/100:
Train Loss: 0.3365, Train Acc: 0.7351
Val Loss: 0.3894, Val Acc: 0.6991
New best model saved!
Epoch 6/100:
Train Loss: 0.3372, Train Acc: 0.7332
Val Loss: 0.3874, Val Acc: 0.6991
New best model saved!
Epoch 7/100:
Train Loss: 0.3500, Train Acc: 0.7255
Val Loss: 0.3859, Val Acc: 0.6991
New best model saved!
Epoch 8/100:
Train Loss: 0.3660, Train Acc: 0.6967
Val Loss: 0.3843, Val Acc: 0.6991
New best model saved!
Epoch 9/100:
Train Loss: 0.3680, Train Acc: 0.7140
Val Loss: 0.3822, Val Acc: 0.6991
New best model saved!
Epoch 10/100:
Train Loss: 0.3353, Train Acc: 0.7370
Val Loss: 0.3796, Val Acc: 0.6991
New best model saved!
Epoch 11/100:
Train Loss: 0.3468, Train Acc: 0.6987
Val Loss: 0.3783, Val Acc: 0.6991
New best model saved!
Epoch 12/100:
Train Loss: 0.3298, Train Acc: 0.6852
Val Loss: 0.3774, Val Acc: 0.6991
New best model saved!
Epoch 13/100:
Train Loss: 0.3473, Train Acc: 0.7179
Val Loss: 0.3768, Val Acc: 0.6991
New best model saved!
Epoch 14/100:
Train Loss: 0.3378, Train Acc: 0.7025
Val Loss: 0.3762, Val Acc: 0.6991
New best model saved!
Epoch 15/100:
Train Loss: 0.3636, Train Acc: 0.7274
Val Loss: 0.3756, Val Acc: 0.6991
New best model saved!
Epoch 16/100:
Train Loss: 0.3558, Train Acc: 0.7006
Val Loss: 0.3741, Val Acc: 0.6991
New best model saved!
Epoch 17/100:
Train Loss: 0.3512, Train Acc: 0.6967
Val Loss: 0.3727, Val Acc: 0.6991
New best model saved!
Epoch 18/100:
Train Loss: 0.3420, Train Acc: 0.6948
Val Loss: 0.3716, Val Acc: 0.6991
New best model saved!
Epoch 19/100:
Train Loss: 0.3311, Train Acc: 0.6891
Val Loss: 0.3711, Val Acc: 0.6991
New best model saved!
Epoch 20/100:
Train Loss: 0.3375, Train Acc: 0.6967
Val Loss: 0.3707, Val Acc: 0.6991
New best model saved!
Epoch 21/100:
Train Loss: 0.3346, Train Acc: 0.6564
Val Loss: 0.3705, Val Acc: 0.6991
New best model saved!
Epoch 22/100:
Train Loss: 0.3525, Train Acc: 0.7063
Val Loss: 0.3701, Val Acc: 0.6991
New best model saved!
Epoch 23/100:
Train Loss: 0.3288, Train Acc: 0.6526
Val Loss: 0.3692, Val Acc: 0.6991
New best model saved!
Epoch 24/100:
Train Loss: 0.3273, Train Acc: 0.6718
Val Loss: 0.3690, Val Acc: 0.6991
New best model saved!
Epoch 25/100:
Train Loss: 0.3353, Train Acc: 0.6852
Val Loss: 0.3690, Val Acc: 0.6991
Epoch 26/100:
Train Loss: 0.3510, Train Acc: 0.6718
Val Loss: 0.3688, Val Acc: 0.6991
New best model saved!
Epoch 27/100:
Train Loss: 0.3538, Train Acc: 0.6775
Val Loss: 0.3685, Val Acc: 0.6991
New best model saved!
Epoch 28/100:
Train Loss: 0.3428, Train Acc: 0.6679
Val Loss: 0.3681, Val Acc: 0.6991
New best model saved!
Epoch 29/100:
Train Loss: 0.3491, Train Acc: 0.6334
Val Loss: 0.3676, Val Acc: 0.6991
New best model saved!
Epoch 30/100:
Train Loss: 0.3252, Train Acc: 0.6929
Val Loss: 0.3671, Val Acc: 0.6991
New best model saved!
Epoch 31/100:
Train Loss: 0.3284, Train Acc: 0.6641
Val Loss: 0.3671, Val Acc: 0.6991
New best model saved!
Epoch 32/100:
Train Loss: 0.3379, Train Acc: 0.6449
Val Loss: 0.3673, Val Acc: 0.6991
Epoch 33/100:
Train Loss: 0.3462, Train Acc: 0.6641
Val Loss: 0.3671, Val Acc: 0.6991
Epoch 34/100:
Train Loss: 0.3438, Train Acc: 0.6276
Val Loss: 0.3668, Val Acc: 0.6991
New best model saved!
Epoch 35/100:
Train Loss: 0.3372, Train Acc: 0.6238
Val Loss: 0.3665, Val Acc: 0.6991
New best model saved!
Epoch 36/100:
Train Loss: 0.3431, Train Acc: 0.6315
Val Loss: 0.3664, Val Acc: 0.6991
New best model saved!
Epoch 37/100:
Train Loss: 0.3312, Train Acc: 0.6315
Val Loss: 0.3663, Val Acc: 0.6903
New best model saved!
Epoch 38/100:
Train Loss: 0.3474, Train Acc: 0.6411
Val Loss: 0.3665, Val Acc: 0.6991
Epoch 39/100:
Train Loss: 0.3385, Train Acc: 0.6180
Val Loss: 0.3664, Val Acc: 0.6903
Epoch 40/100:
Train Loss: 0.3379, Train Acc: 0.6430
Val Loss: 0.3663, Val Acc: 0.6903
New best model saved!
Epoch 41/100:
Train Loss: 0.3476, Train Acc: 0.6276
Val Loss: 0.3662, Val Acc: 0.6903
New best model saved!
Epoch 42/100:
Train Loss: 0.3573, Train Acc: 0.6219
Val Loss: 0.3657, Val Acc: 0.6549
New best model saved!
Epoch 43/100:
Train Loss: 0.3314, Train Acc: 0.6084
Val Loss: 0.3653, Val Acc: 0.6106
New best model saved!
Epoch 44/100:
Train Loss: 0.3451, Train Acc: 0.6411
Val Loss: 0.3653, Val Acc: 0.6195
New best model saved!
Epoch 45/100:
Train Loss: 0.3335, Train Acc: 0.6142
Val Loss: 0.3649, Val Acc: 0.5664
New best model saved!
Epoch 46/100:
Train Loss: 0.3444, Train Acc: 0.6756
Val Loss: 0.3649, Val Acc: 0.5752
New best model saved!
Epoch 47/100:
Train Loss: 0.3404, Train Acc: 0.6027
Val Loss: 0.3648, Val Acc: 0.5841
New best model saved!
Epoch 48/100:
Train Loss: 0.3487, Train Acc: 0.6123
Val Loss: 0.3648, Val Acc: 0.5841
New best model saved!
Epoch 49/100:
Train Loss: 0.3498, Train Acc: 0.6027
Val Loss: 0.3646, Val Acc: 0.5664
New best model saved!
Epoch 50/100:
Train Loss: 0.3526, Train Acc: 0.5720
Val Loss: 0.3643, Val Acc: 0.4956
New best model saved!
Epoch 51/100:
Train Loss: 0.3462, Train Acc: 0.5835
Val Loss: 0.3640, Val Acc: 0.5221
New best model saved!
Epoch 52/100:
Train Loss: 0.3521, Train Acc: 0.5797
Val Loss: 0.3639, Val Acc: 0.4956
New best model saved!
Epoch 53/100:
Train Loss: 0.3570, Train Acc: 0.5643
Val Loss: 0.3638, Val Acc: 0.4690
New best model saved!
Epoch 54/100:
Train Loss: 0.3517, Train Acc: 0.5816
Val Loss: 0.3637, Val Acc: 0.4336
New best model saved!
Epoch 55/100:
Train Loss: 0.3420, Train Acc: 0.5489
Val Loss: 0.3636, Val Acc: 0.4071
New best model saved!
Epoch 56/100:
Train Loss: 0.3438, Train Acc: 0.5259
Val Loss: 0.3636, Val Acc: 0.4071
New best model saved!
Epoch 57/100:
Train Loss: 0.3375, Train Acc: 0.5624
Val Loss: 0.3636, Val Acc: 0.3982
Epoch 58/100:
Train Loss: 0.3383, Train Acc: 0.5451
Val Loss: 0.3636, Val Acc: 0.3982
Epoch 59/100:
Train Loss: 0.3413, Train Acc: 0.5470
Val Loss: 0.3636, Val Acc: 0.3982
Epoch 60/100:
Train Loss: 0.3460, Train Acc: 0.5451
Val Loss: 0.3637, Val Acc: 0.3894
Epoch 61/100:
Train Loss: 0.3338, Train Acc: 0.5797
Val Loss: 0.3637, Val Acc: 0.3540
Epoch 62/100:
Train Loss: 0.3454, Train Acc: 0.5202
Val Loss: 0.3636, Val Acc: 0.3363
Epoch 63/100:
Train Loss: 0.3460, Train Acc: 0.5317
Val Loss: 0.3636, Val Acc: 0.3274
Epoch 64/100:
Train Loss: 0.3361, Train Acc: 0.5566
Val Loss: 0.3636, Val Acc: 0.3186
Epoch 65/100:
Train Loss: 0.3414, Train Acc: 0.5086
Val Loss: 0.3636, Val Acc: 0.3363
Epoch 66/100:
Train Loss: 0.3441, Train Acc: 0.5355
Val Loss: 0.3636, Val Acc: 0.3894
Early stopping triggered after 66 epochs!
Loaded best model from ../results/models/eye/0.pth
Running Experiment on Fold 1

  0%|          | 0/25 [00:00<?, ?it/s]

  0%|          | 0/593 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/74 [00:00<?, ?it/s]

Participant 407 is missing at least one modality (EYE)

  0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/92 [00:00<?, ?it/s]

/home/ammar/MultimodalEngagement/Modeling/notebooks/../src/models/multimodal_fusion.py:73: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  criterion = nn.BCEWithLogitsLoss(pos_weight=torch.tensor(pos_weight).to(device))

Epochs:   0%|          | 0/100 [00:00<?, ?it/s]

Epoch 1/100:
Train Loss: 0.3862, Train Acc: 0.3423
Val Loss: 0.3680, Val Acc: 0.1892
New best model saved!
Epoch 2/100:
Train Loss: 0.3804, Train Acc: 0.3828
Val Loss: 0.3675, Val Acc: 0.1892
New best model saved!
Epoch 3/100:
Train Loss: 0.3776, Train Acc: 0.3777
Val Loss: 0.3666, Val Acc: 0.2162
New best model saved!
Epoch 4/100:
Train Loss: 0.3845, Train Acc: 0.3761
Val Loss: 0.3659, Val Acc: 0.2297
New best model saved!
Epoch 5/100:
Train Loss: 0.3849, Train Acc: 0.3828
Val Loss: 0.3654, Val Acc: 0.2703
New best model saved!
Epoch 6/100:
Train Loss: 0.3801, Train Acc: 0.3811
Val Loss: 0.3650, Val Acc: 0.2838
New best model saved!
Epoch 7/100:
Train Loss: 0.3811, Train Acc: 0.3963
Val Loss: 0.3647, Val Acc: 0.2838
New best model saved!
Epoch 8/100:
Train Loss: 0.3844, Train Acc: 0.4418
Val Loss: 0.3645, Val Acc: 0.2838
New best model saved!
Epoch 9/100:
Train Loss: 0.3815, Train Acc: 0.4165
Val Loss: 0.3645, Val Acc: 0.2838
New best model saved!
Epoch 10/100:
Train Loss: 0.3755, Train Acc: 0.4199
Val Loss: 0.3644, Val Acc: 0.2838
New best model saved!
Epoch 11/100:
Train Loss: 0.3813, Train Acc: 0.4755
Val Loss: 0.3642, Val Acc: 0.2973
New best model saved!
Epoch 12/100:
Train Loss: 0.3750, Train Acc: 0.4621
Val Loss: 0.3641, Val Acc: 0.3108
New best model saved!
Epoch 13/100:
Train Loss: 0.3800, Train Acc: 0.4806
Val Loss: 0.3639, Val Acc: 0.2973
New best model saved!
Epoch 14/100:
Train Loss: 0.3777, Train Acc: 0.4688
Val Loss: 0.3638, Val Acc: 0.3108
New best model saved!
Epoch 15/100:
Train Loss: 0.3754, Train Acc: 0.4907
Val Loss: 0.3637, Val Acc: 0.3243
New best model saved!
Epoch 16/100:
Train Loss: 0.3801, Train Acc: 0.4722
Val Loss: 0.3636, Val Acc: 0.3378
New best model saved!
Epoch 17/100:
Train Loss: 0.3800, Train Acc: 0.4654
Val Loss: 0.3636, Val Acc: 0.3378
New best model saved!
Epoch 18/100:
Train Loss: 0.3823, Train Acc: 0.4941
Val Loss: 0.3636, Val Acc: 0.3784
Epoch 19/100:
Train Loss: 0.3844, Train Acc: 0.4890
Val Loss: 0.3636, Val Acc: 0.3784
New best model saved!
Epoch 20/100:
Train Loss: 0.3753, Train Acc: 0.4840
Val Loss: 0.3636, Val Acc: 0.3784
New best model saved!
Epoch 21/100:
Train Loss: 0.3817, Train Acc: 0.5093
Val Loss: 0.3637, Val Acc: 0.3649
Epoch 22/100:
Train Loss: 0.3810, Train Acc: 0.5042
Val Loss: 0.3639, Val Acc: 0.3649
Epoch 23/100:
Train Loss: 0.3804, Train Acc: 0.5025
Val Loss: 0.3639, Val Acc: 0.3784
Epoch 24/100:
Train Loss: 0.3882, Train Acc: 0.5025
Val Loss: 0.3640, Val Acc: 0.3784
Epoch 25/100:
Train Loss: 0.3790, Train Acc: 0.5396
Val Loss: 0.3640, Val Acc: 0.3649
Epoch 26/100:
Train Loss: 0.3802, Train Acc: 0.5177
Val Loss: 0.3640, Val Acc: 0.3649
Epoch 27/100:
Train Loss: 0.3787, Train Acc: 0.4924
Val Loss: 0.3640, Val Acc: 0.3649
Epoch 28/100:
Train Loss: 0.3768, Train Acc: 0.5059
Val Loss: 0.3641, Val Acc: 0.3919
Epoch 29/100:
Train Loss: 0.3809, Train Acc: 0.5312
Val Loss: 0.3643, Val Acc: 0.4459
Epoch 30/100:
Train Loss: 0.3739, Train Acc: 0.5278
Val Loss: 0.3643, Val Acc: 0.4595
Early stopping triggered after 30 epochs!
Loaded best model from ../results/models/eye/1.pth
Running Experiment on Fold 2
Participant 407 is missing at least one modality (EYE)

  0%|          | 0/23 [00:00<?, ?it/s]

  0%|          | 0/501 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/103 [00:00<?, ?it/s]

  0%|          | 0/6 [00:00<?, ?it/s]

  0%|          | 0/155 [00:00<?, ?it/s]

/home/ammar/MultimodalEngagement/Modeling/notebooks/../src/models/multimodal_fusion.py:73: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  criterion = nn.BCEWithLogitsLoss(pos_weight=torch.tensor(pos_weight).to(device))

Epochs:   0%|          | 0/100 [00:00<?, ?it/s]

Epoch 1/100:
Train Loss: 0.3704, Train Acc: 0.6846
Val Loss: 0.3438, Val Acc: 0.6214
New best model saved!
Epoch 2/100:
Train Loss: 0.3690, Train Acc: 0.6607
Val Loss: 0.3442, Val Acc: 0.5922
Epoch 3/100:
Train Loss: 0.3665, Train Acc: 0.6946
Val Loss: 0.3440, Val Acc: 0.6019
Epoch 4/100:
Train Loss: 0.3677, Train Acc: 0.6747
Val Loss: 0.3445, Val Acc: 0.5922
Epoch 5/100:
Train Loss: 0.3690, Train Acc: 0.6806
Val Loss: 0.3446, Val Acc: 0.5922
Epoch 6/100:
Train Loss: 0.3672, Train Acc: 0.6926
Val Loss: 0.3444, Val Acc: 0.6019
Epoch 7/100:
Train Loss: 0.3684, Train Acc: 0.6687
Val Loss: 0.3440, Val Acc: 0.6019
Epoch 8/100:
Train Loss: 0.3702, Train Acc: 0.6647
Val Loss: 0.3443, Val Acc: 0.5922
Epoch 9/100:
Train Loss: 0.3686, Train Acc: 0.6766
Val Loss: 0.3442, Val Acc: 0.5922
Epoch 10/100:
Train Loss: 0.3693, Train Acc: 0.6527
Val Loss: 0.3445, Val Acc: 0.5922
Epoch 11/100:
Train Loss: 0.3669, Train Acc: 0.6707
Val Loss: 0.3444, Val Acc: 0.5922
Early stopping triggered after 11 epochs!
Loaded best model from ../results/models/eye/2.pth
Running Experiment on Fold 3
Participant 407 is missing at least one modality (EYE)

  0%|          | 0/23 [00:00<?, ?it/s]

  0%|          | 0/521 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/104 [00:00<?, ?it/s]

  0%|          | 0/6 [00:00<?, ?it/s]

  0%|          | 0/134 [00:00<?, ?it/s]

/home/ammar/MultimodalEngagement/Modeling/notebooks/../src/models/multimodal_fusion.py:73: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  criterion = nn.BCEWithLogitsLoss(pos_weight=torch.tensor(pos_weight).to(device))

Epochs:   0%|          | 0/100 [00:00<?, ?it/s]

Epoch 1/100:
Train Loss: 0.3651, Train Acc: 0.7236
Val Loss: 0.3184, Val Acc: 0.8269
New best model saved!
Epoch 2/100:
Train Loss: 0.3827, Train Acc: 0.7198
Val Loss: 0.3189, Val Acc: 0.8269
Epoch 3/100:
Train Loss: 0.3725, Train Acc: 0.7121
Val Loss: 0.3200, Val Acc: 0.8269
Epoch 4/100:
Train Loss: 0.3802, Train Acc: 0.7083
Val Loss: 0.3213, Val Acc: 0.8269
Epoch 5/100:
Train Loss: 0.3813, Train Acc: 0.7102
Val Loss: 0.3225, Val Acc: 0.8269
Epoch 6/100:
Train Loss: 0.3775, Train Acc: 0.6910
Val Loss: 0.3241, Val Acc: 0.8269
Epoch 7/100:
Train Loss: 0.3867, Train Acc: 0.6871
Val Loss: 0.3251, Val Acc: 0.8269
Epoch 8/100:
Train Loss: 0.3837, Train Acc: 0.7179
Val Loss: 0.3264, Val Acc: 0.8269
Epoch 9/100:
Train Loss: 0.3797, Train Acc: 0.6545
Val Loss: 0.3281, Val Acc: 0.8365
Epoch 10/100:
Train Loss: 0.3868, Train Acc: 0.7063
Val Loss: 0.3296, Val Acc: 0.8077
Epoch 11/100:
Train Loss: 0.3802, Train Acc: 0.6718
Val Loss: 0.3312, Val Acc: 0.6827
Early stopping triggered after 11 epochs!
Loaded best model from ../results/models/eye/3.pth
Running Experiment on Fold 4
Participant 407 is missing at least one modality (EYE)

/home/ammar/miniconda3/envs/torch/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/ammar/miniconda3/envs/torch/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/ammar/miniconda3/envs/torch/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

  0%|          | 0/24 [00:00<?, ?it/s]

  0%|          | 0/561 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/91 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/107 [00:00<?, ?it/s]

/home/ammar/MultimodalEngagement/Modeling/notebooks/../src/models/multimodal_fusion.py:73: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  criterion = nn.BCEWithLogitsLoss(pos_weight=torch.tensor(pos_weight).to(device))

Epochs:   0%|          | 0/100 [00:00<?, ?it/s]

Epoch 1/100:
Train Loss: 0.4028, Train Acc: 0.6043
Val Loss: 0.3658, Val Acc: 0.7802
New best model saved!
Epoch 2/100:
Train Loss: 0.4001, Train Acc: 0.6078
Val Loss: 0.3660, Val Acc: 0.7802
Epoch 3/100:
Train Loss: 0.3980, Train Acc: 0.6168
Val Loss: 0.3661, Val Acc: 0.7802
Epoch 4/100:
Train Loss: 0.4032, Train Acc: 0.5918
Val Loss: 0.3662, Val Acc: 0.7802
Epoch 5/100:
Train Loss: 0.4022, Train Acc: 0.5686
Val Loss: 0.3664, Val Acc: 0.7692
Epoch 6/100:
Train Loss: 0.4033, Train Acc: 0.5865
Val Loss: 0.3664, Val Acc: 0.7692
Epoch 7/100:
Train Loss: 0.4012, Train Acc: 0.5918
Val Loss: 0.3665, Val Acc: 0.7692
Epoch 8/100:
Train Loss: 0.3959, Train Acc: 0.6132
Val Loss: 0.3667, Val Acc: 0.7692
Epoch 9/100:
Train Loss: 0.3964, Train Acc: 0.5936
Val Loss: 0.3669, Val Acc: 0.7692
Epoch 10/100:
Train Loss: 0.4057, Train Acc: 0.5508
Val Loss: 0.3670, Val Acc: 0.7692
Epoch 11/100:
Train Loss: 0.4040, Train Acc: 0.5811
Val Loss: 0.3669, Val Acc: 0.7692
Early stopping triggered after 11 epochs!
Loaded best model from ../results/models/eye/4.pth
Running Experiment on Fold 5
Participant 407 is missing at least one modality (EYE)

/home/ammar/miniconda3/envs/torch/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/ammar/miniconda3/envs/torch/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/ammar/miniconda3/envs/torch/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

  0%|          | 0/23 [00:00<?, ?it/s]

  0%|          | 0/517 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/96 [00:00<?, ?it/s]

  0%|          | 0/6 [00:00<?, ?it/s]

  0%|          | 0/146 [00:00<?, ?it/s]

/home/ammar/MultimodalEngagement/Modeling/notebooks/../src/models/multimodal_fusion.py:73: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  criterion = nn.BCEWithLogitsLoss(pos_weight=torch.tensor(pos_weight).to(device))

Epochs:   0%|          | 0/100 [00:00<?, ?it/s]

Epoch 1/100:
Train Loss: 0.4134, Train Acc: 0.5899
Val Loss: 0.3843, Val Acc: 0.7292
New best model saved!
Epoch 2/100:
Train Loss: 0.4031, Train Acc: 0.5783
Val Loss: 0.3843, Val Acc: 0.7292
Epoch 3/100:
Train Loss: 0.3977, Train Acc: 0.5783
Val Loss: 0.3843, Val Acc: 0.7292
Epoch 4/100:
Train Loss: 0.4123, Train Acc: 0.5803
Val Loss: 0.3843, Val Acc: 0.7292
New best model saved!
Epoch 5/100:
Train Loss: 0.3960, Train Acc: 0.5957
Val Loss: 0.3843, Val Acc: 0.7292
Epoch 6/100:
Train Loss: 0.3989, Train Acc: 0.6306
Val Loss: 0.3843, Val Acc: 0.7292
Epoch 7/100:
Train Loss: 0.4228, Train Acc: 0.6209
Val Loss: 0.3843, Val Acc: 0.7292
Epoch 8/100:
Train Loss: 0.4119, Train Acc: 0.6151
Val Loss: 0.3843, Val Acc: 0.7292
Epoch 9/100:
Train Loss: 0.4198, Train Acc: 0.5861
Val Loss: 0.3843, Val Acc: 0.7292
Epoch 10/100:
Train Loss: 0.4059, Train Acc: 0.6190
Val Loss: 0.3844, Val Acc: 0.7292
Epoch 11/100:
Train Loss: 0.4140, Train Acc: 0.5783
Val Loss: 0.3843, Val Acc: 0.7292
Epoch 12/100:
Train Loss: 0.3943, Train Acc: 0.5783
Val Loss: 0.3843, Val Acc: 0.7292
Epoch 13/100:
Train Loss: 0.4129, Train Acc: 0.6248
Val Loss: 0.3843, Val Acc: 0.7292
Epoch 14/100:
Train Loss: 0.4069, Train Acc: 0.6267
Val Loss: 0.3842, Val Acc: 0.7292
New best model saved!
Epoch 15/100:
Train Loss: 0.3939, Train Acc: 0.6093
Val Loss: 0.3842, Val Acc: 0.7292
New best model saved!
Epoch 16/100:
Train Loss: 0.4133, Train Acc: 0.6228
Val Loss: 0.3841, Val Acc: 0.7292
New best model saved!
Epoch 17/100:
Train Loss: 0.4149, Train Acc: 0.6093
Val Loss: 0.3841, Val Acc: 0.7292
New best model saved!
Epoch 18/100:
Train Loss: 0.3962, Train Acc: 0.6151
Val Loss: 0.3840, Val Acc: 0.7292
New best model saved!
Epoch 19/100:
Train Loss: 0.4060, Train Acc: 0.6248
Val Loss: 0.3840, Val Acc: 0.7292
New best model saved!
Epoch 20/100:
Train Loss: 0.3821, Train Acc: 0.6170
Val Loss: 0.3839, Val Acc: 0.7292
New best model saved!
Epoch 21/100:
Train Loss: 0.4036, Train Acc: 0.6267
Val Loss: 0.3839, Val Acc: 0.7292
New best model saved!
Epoch 22/100:
Train Loss: 0.4161, Train Acc: 0.6132
Val Loss: 0.3839, Val Acc: 0.7292
New best model saved!
Epoch 23/100:
Train Loss: 0.4334, Train Acc: 0.6228
Val Loss: 0.3839, Val Acc: 0.7292
Epoch 24/100:
Train Loss: 0.3903, Train Acc: 0.6499
Val Loss: 0.3839, Val Acc: 0.7292
Epoch 25/100:
Train Loss: 0.4262, Train Acc: 0.6499
Val Loss: 0.3839, Val Acc: 0.7292
Epoch 26/100:
Train Loss: 0.3934, Train Acc: 0.6267
Val Loss: 0.3840, Val Acc: 0.7292
Epoch 27/100:
Train Loss: 0.4019, Train Acc: 0.6344
Val Loss: 0.3840, Val Acc: 0.7292
Epoch 28/100:
Train Loss: 0.4183, Train Acc: 0.6248
Val Loss: 0.3840, Val Acc: 0.7292
Epoch 29/100:
Train Loss: 0.3984, Train Acc: 0.6190
Val Loss: 0.3841, Val Acc: 0.7292
Epoch 30/100:
Train Loss: 0.4074, Train Acc: 0.5532
Val Loss: 0.3841, Val Acc: 0.7292
Epoch 31/100:
Train Loss: 0.4020, Train Acc: 0.6190
Val Loss: 0.3840, Val Acc: 0.7292
Epoch 32/100:
Train Loss: 0.3915, Train Acc: 0.5803
Val Loss: 0.3840, Val Acc: 0.7292
Early stopping triggered after 32 epochs!
Loaded best model from ../results/models/eye/5.pth
Running Experiment on Fold 6
Participant 407 is missing at least one modality (EYE)

/home/ammar/miniconda3/envs/torch/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/ammar/miniconda3/envs/torch/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/ammar/miniconda3/envs/torch/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

  0%|          | 0/29 [00:00<?, ?it/s]

  0%|          | 0/676 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/83 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/115 [00:00<?, ?it/s]

/home/ammar/MultimodalEngagement/Modeling/notebooks/../src/models/multimodal_fusion.py:73: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  criterion = nn.BCEWithLogitsLoss(pos_weight=torch.tensor(pos_weight).to(device))

Epochs:   0%|          | 0/100 [00:00<?, ?it/s]

Epoch 1/100:
Train Loss: 0.3646, Train Acc: 0.3018
Val Loss: 0.3996, Val Acc: 0.3253
New best model saved!
Epoch 2/100:
Train Loss: 0.3664, Train Acc: 0.3121
Val Loss: 0.3989, Val Acc: 0.3253
New best model saved!
Epoch 3/100:
Train Loss: 0.3602, Train Acc: 0.3121
Val Loss: 0.3984, Val Acc: 0.3253
New best model saved!
Epoch 4/100:
Train Loss: 0.3647, Train Acc: 0.3254
Val Loss: 0.3982, Val Acc: 0.3253
New best model saved!
Epoch 5/100:
Train Loss: 0.3617, Train Acc: 0.3314
Val Loss: 0.3981, Val Acc: 0.3253
New best model saved!
Epoch 6/100:
Train Loss: 0.3656, Train Acc: 0.3299
Val Loss: 0.3983, Val Acc: 0.3253
Epoch 7/100:
Train Loss: 0.3616, Train Acc: 0.3299
Val Loss: 0.3984, Val Acc: 0.3253
Epoch 8/100:
Train Loss: 0.3618, Train Acc: 0.3550
Val Loss: 0.3988, Val Acc: 0.3253
Epoch 9/100:
Train Loss: 0.3636, Train Acc: 0.3654
Val Loss: 0.3991, Val Acc: 0.3253
Epoch 10/100:
Train Loss: 0.3621, Train Acc: 0.3802
Val Loss: 0.3994, Val Acc: 0.3373
Epoch 11/100:
Train Loss: 0.3596, Train Acc: 0.3950
Val Loss: 0.3997, Val Acc: 0.3253
Epoch 12/100:
Train Loss: 0.3598, Train Acc: 0.4068
Val Loss: 0.4001, Val Acc: 0.3614
Epoch 13/100:
Train Loss: 0.3644, Train Acc: 0.3861
Val Loss: 0.4004, Val Acc: 0.4337
Epoch 14/100:
Train Loss: 0.3605, Train Acc: 0.3743
Val Loss: 0.4010, Val Acc: 0.5904
Epoch 15/100:
Train Loss: 0.3628, Train Acc: 0.4098
Val Loss: 0.4014, Val Acc: 0.6386
Early stopping triggered after 15 epochs!
Loaded best model from ../results/models/eye/6.pth
Accuracy: 0.6413200381403196 ± 0.14714639523502543
ROC-AUC: 0.4900358649783899 ± 0.15082562968220584

/home/ammar/miniconda3/envs/torch/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/ammar/miniconda3/envs/torch/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/ammar/miniconda3/envs/torch/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [4]:
read_reports("../results/tables/eye/")

Accuracy: 0.6413200381403196 ± 0.14714639523502543
ROC-AUC: 0.4900358649783899 ± 0.15082562968220584

                     Low           High            Avg.
Metric
precision    0.18 ± 0.19    0.63 ± 0.28      0.41 ± 0.1
recall       0.27 ± 0.38    0.73 ± 0.38      0.5 ± 0.02
f1-score     0.19 ± 0.25    0.67 ± 0.32     0.43 ± 0.07
support    36.14 ± 11.95  88.71 ± 20.25  124.86 ± 22.12

# OpenFace Only

In [5]:
run_experiment(dataset_root="../../Dataset/", modalities=["OpenFace"], exp_kwargs={"model_kwargs":{"dropout":0.5, "hidden_dim":64}});

Running Experiment on Fold 0
Participant 407 is missing at least one modality (OpenFace)

  0%|          | 0/24 [00:00<?, ?it/s]

  0%|          | 0/521 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/113 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/125 [00:00<?, ?it/s]

/home/ammar/MultimodalEngagement/Modeling/notebooks/../src/models/multimodal_fusion.py:73: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  criterion = nn.BCEWithLogitsLoss(pos_weight=torch.tensor(pos_weight).to(device))

Epochs:   0%|          | 0/100 [00:00<?, ?it/s]

Epoch 1/100:
Train Loss: 0.4480, Train Acc: 0.4453
Val Loss: 0.3727, Val Acc: 0.3805
New best model saved!
Epoch 2/100:
Train Loss: 0.3941, Train Acc: 0.5048
Val Loss: 0.4371, Val Acc: 0.6991
Epoch 3/100:
Train Loss: 0.4252, Train Acc: 0.6084
Val Loss: 0.4477, Val Acc: 0.6991
Epoch 4/100:
Train Loss: 0.3792, Train Acc: 0.5374
Val Loss: 0.3764, Val Acc: 0.6726
Epoch 5/100:
Train Loss: 0.3547, Train Acc: 0.5413
Val Loss: 0.3953, Val Acc: 0.6991
Epoch 6/100:
Train Loss: 0.3709, Train Acc: 0.5854
Val Loss: 0.4065, Val Acc: 0.6991
Epoch 7/100:
Train Loss: 0.3634, Train Acc: 0.5701
Val Loss: 0.3767, Val Acc: 0.6814
Epoch 8/100:
Train Loss: 0.3402, Train Acc: 0.5585
Val Loss: 0.3947, Val Acc: 0.6991
Epoch 9/100:
Train Loss: 0.3505, Train Acc: 0.6315
Val Loss: 0.4283, Val Acc: 0.6991
Epoch 10/100:
Train Loss: 0.3753, Train Acc: 0.6430
Val Loss: 0.3912, Val Acc: 0.6726
Epoch 11/100:
Train Loss: 0.3639, Train Acc: 0.5182
Val Loss: 0.3899, Val Acc: 0.5398
Early stopping triggered after 11 epochs!
Loaded best model from ../results/models/openface/0.pth
Running Experiment on Fold 1

  0%|          | 0/25 [00:00<?, ?it/s]

  0%|          | 0/593 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/74 [00:00<?, ?it/s]

Participant 407 is missing at least one modality (OpenFace)

  0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/92 [00:00<?, ?it/s]

/home/ammar/MultimodalEngagement/Modeling/notebooks/../src/models/multimodal_fusion.py:73: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  criterion = nn.BCEWithLogitsLoss(pos_weight=torch.tensor(pos_weight).to(device))

Epochs:   0%|          | 0/100 [00:00<?, ?it/s]

Epoch 1/100:
Train Loss: 0.4296, Train Acc: 0.5750
Val Loss: 0.3326, Val Acc: 0.7297
New best model saved!
Epoch 2/100:
Train Loss: 0.3919, Train Acc: 0.5497
Val Loss: 0.3285, Val Acc: 0.7568
New best model saved!
Epoch 3/100:
Train Loss: 0.3945, Train Acc: 0.5261
Val Loss: 0.3307, Val Acc: 0.7162
Epoch 4/100:
Train Loss: 0.4099, Train Acc: 0.5497
Val Loss: 0.3208, Val Acc: 0.7838
New best model saved!
Epoch 5/100:
Train Loss: 0.4107, Train Acc: 0.5548
Val Loss: 0.3348, Val Acc: 0.5946
Epoch 6/100:
Train Loss: 0.4133, Train Acc: 0.4823
Val Loss: 0.3456, Val Acc: 0.3919
Epoch 7/100:
Train Loss: 0.4382, Train Acc: 0.4604
Val Loss: 0.3401, Val Acc: 0.4730
Epoch 8/100:
Train Loss: 0.3877, Train Acc: 0.5312
Val Loss: 0.3302, Val Acc: 0.7973
Epoch 9/100:
Train Loss: 0.3820, Train Acc: 0.5902
Val Loss: 0.3276, Val Acc: 0.8108
Epoch 10/100:
Train Loss: 0.3823, Train Acc: 0.5885
Val Loss: 0.3318, Val Acc: 0.7162
Epoch 11/100:
Train Loss: 0.3873, Train Acc: 0.5666
Val Loss: 0.3258, Val Acc: 0.7973
Epoch 12/100:
Train Loss: 0.3855, Train Acc: 0.5970
Val Loss: 0.3249, Val Acc: 0.8108
Epoch 13/100:
Train Loss: 0.3944, Train Acc: 0.5599
Val Loss: 0.3384, Val Acc: 0.4459
Epoch 14/100:
Train Loss: 0.3839, Train Acc: 0.4688
Val Loss: 0.3388, Val Acc: 0.3919
Early stopping triggered after 14 epochs!
Loaded best model from ../results/models/openface/1.pth
Running Experiment on Fold 2
Participant 407 is missing at least one modality (OpenFace)

  0%|          | 0/23 [00:00<?, ?it/s]

  0%|          | 0/501 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/103 [00:00<?, ?it/s]

  0%|          | 0/6 [00:00<?, ?it/s]

  0%|          | 0/155 [00:00<?, ?it/s]

/home/ammar/MultimodalEngagement/Modeling/notebooks/../src/models/multimodal_fusion.py:73: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  criterion = nn.BCEWithLogitsLoss(pos_weight=torch.tensor(pos_weight).to(device))

Epochs:   0%|          | 0/100 [00:00<?, ?it/s]

Epoch 1/100:
Train Loss: 0.4326, Train Acc: 0.5549
Val Loss: 0.3523, Val Acc: 0.2427
New best model saved!
Epoch 2/100:
Train Loss: 0.4063, Train Acc: 0.3932
Val Loss: 0.3413, Val Acc: 0.3204
New best model saved!
Epoch 3/100:
Train Loss: 0.3915, Train Acc: 0.4531
Val Loss: 0.3147, Val Acc: 0.7864
New best model saved!
Epoch 4/100:
Train Loss: 0.3905, Train Acc: 0.5549
Val Loss: 0.3178, Val Acc: 0.7864
Epoch 5/100:
Train Loss: 0.3862, Train Acc: 0.5429
Val Loss: 0.3243, Val Acc: 0.7282
Epoch 6/100:
Train Loss: 0.3706, Train Acc: 0.5090
Val Loss: 0.3315, Val Acc: 0.6408
Epoch 7/100:
Train Loss: 0.3886, Train Acc: 0.4850
Val Loss: 0.3231, Val Acc: 0.7379
Epoch 8/100:
Train Loss: 0.3965, Train Acc: 0.4950
Val Loss: 0.3360, Val Acc: 0.5049
Epoch 9/100:
Train Loss: 0.3762, Train Acc: 0.4511
Val Loss: 0.3273, Val Acc: 0.6893
Epoch 10/100:
Train Loss: 0.3618, Train Acc: 0.5389
Val Loss: 0.3198, Val Acc: 0.7864
Epoch 11/100:
Train Loss: 0.3731, Train Acc: 0.5329
Val Loss: 0.3201, Val Acc: 0.7864
Epoch 12/100:
Train Loss: 0.3620, Train Acc: 0.5709
Val Loss: 0.3208, Val Acc: 0.7864
Epoch 13/100:
Train Loss: 0.3666, Train Acc: 0.5529
Val Loss: 0.3245, Val Acc: 0.7282
Early stopping triggered after 13 epochs!
Loaded best model from ../results/models/openface/2.pth
Running Experiment on Fold 3
Participant 407 is missing at least one modality (OpenFace)

  0%|          | 0/23 [00:00<?, ?it/s]

  0%|          | 0/521 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/104 [00:00<?, ?it/s]

  0%|          | 0/6 [00:00<?, ?it/s]

  0%|          | 0/134 [00:00<?, ?it/s]

/home/ammar/MultimodalEngagement/Modeling/notebooks/../src/models/multimodal_fusion.py:73: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  criterion = nn.BCEWithLogitsLoss(pos_weight=torch.tensor(pos_weight).to(device))

Epochs:   0%|          | 0/100 [00:00<?, ?it/s]

Epoch 1/100:
Train Loss: 0.4232, Train Acc: 0.4223
Val Loss: 0.3089, Val Acc: 0.8077
New best model saved!
Epoch 2/100:
Train Loss: 0.4120, Train Acc: 0.5585
Val Loss: 0.3063, Val Acc: 0.8077
New best model saved!
Epoch 3/100:
Train Loss: 0.4107, Train Acc: 0.5585
Val Loss: 0.3305, Val Acc: 0.7019
Epoch 4/100:
Train Loss: 0.3917, Train Acc: 0.5432
Val Loss: 0.3418, Val Acc: 0.5962
Epoch 5/100:
Train Loss: 0.3891, Train Acc: 0.5393
Val Loss: 0.3291, Val Acc: 0.7308
Epoch 6/100:
Train Loss: 0.3826, Train Acc: 0.5336
Val Loss: 0.3433, Val Acc: 0.5288
Epoch 7/100:
Train Loss: 0.3917, Train Acc: 0.4933
Val Loss: 0.3396, Val Acc: 0.5769
Epoch 8/100:
Train Loss: 0.3948, Train Acc: 0.5701
Val Loss: 0.3134, Val Acc: 0.8173
Epoch 9/100:
Train Loss: 0.3836, Train Acc: 0.5777
Val Loss: 0.3505, Val Acc: 0.4038
Epoch 10/100:
Train Loss: 0.3880, Train Acc: 0.5086
Val Loss: 0.3629, Val Acc: 0.2019
Epoch 11/100:
Train Loss: 0.3665, Train Acc: 0.4990
Val Loss: 0.3504, Val Acc: 0.4423
Epoch 12/100:
Train Loss: 0.3730, Train Acc: 0.5854
Val Loss: 0.3221, Val Acc: 0.8077
Early stopping triggered after 12 epochs!
Loaded best model from ../results/models/openface/3.pth
Running Experiment on Fold 4
Participant 407 is missing at least one modality (OpenFace)

  0%|          | 0/24 [00:00<?, ?it/s]

  0%|          | 0/561 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/91 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/107 [00:00<?, ?it/s]

/home/ammar/MultimodalEngagement/Modeling/notebooks/../src/models/multimodal_fusion.py:73: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  criterion = nn.BCEWithLogitsLoss(pos_weight=torch.tensor(pos_weight).to(device))

Epochs:   0%|          | 0/100 [00:00<?, ?it/s]

Epoch 1/100:
Train Loss: 0.4468, Train Acc: 0.5740
Val Loss: 0.3991, Val Acc: 0.3956
New best model saved!
Epoch 2/100:
Train Loss: 0.4619, Train Acc: 0.4724
Val Loss: 0.3637, Val Acc: 0.6264
New best model saved!
Epoch 3/100:
Train Loss: 0.4374, Train Acc: 0.5651
Val Loss: 0.3539, Val Acc: 0.8022
New best model saved!
Epoch 4/100:
Train Loss: 0.4317, Train Acc: 0.6275
Val Loss: 0.3555, Val Acc: 0.7692
Epoch 5/100:
Train Loss: 0.4079, Train Acc: 0.5455
Val Loss: 0.3845, Val Acc: 0.3846
Epoch 6/100:
Train Loss: 0.4232, Train Acc: 0.4991
Val Loss: 0.3675, Val Acc: 0.4835
Epoch 7/100:
Train Loss: 0.4105, Train Acc: 0.5865
Val Loss: 0.3630, Val Acc: 0.6044
Epoch 8/100:
Train Loss: 0.4169, Train Acc: 0.5811
Val Loss: 0.3599, Val Acc: 0.7253
Epoch 9/100:
Train Loss: 0.4079, Train Acc: 0.5900
Val Loss: 0.3622, Val Acc: 0.6044
Epoch 10/100:
Train Loss: 0.4014, Train Acc: 0.6506
Val Loss: 0.3564, Val Acc: 0.7802
Epoch 11/100:
Train Loss: 0.4082, Train Acc: 0.6684
Val Loss: 0.3572, Val Acc: 0.7582
Epoch 12/100:
Train Loss: 0.4018, Train Acc: 0.6399
Val Loss: 0.3635, Val Acc: 0.6044
Epoch 13/100:
Train Loss: 0.3984, Train Acc: 0.5918
Val Loss: 0.3658, Val Acc: 0.4835
Early stopping triggered after 13 epochs!
Loaded best model from ../results/models/openface/4.pth
Running Experiment on Fold 5
Participant 407 is missing at least one modality (OpenFace)

/home/ammar/miniconda3/envs/torch/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/ammar/miniconda3/envs/torch/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/ammar/miniconda3/envs/torch/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

  0%|          | 0/23 [00:00<?, ?it/s]

  0%|          | 0/517 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/96 [00:00<?, ?it/s]

  0%|          | 0/6 [00:00<?, ?it/s]

  0%|          | 0/146 [00:00<?, ?it/s]

/home/ammar/MultimodalEngagement/Modeling/notebooks/../src/models/multimodal_fusion.py:73: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  criterion = nn.BCEWithLogitsLoss(pos_weight=torch.tensor(pos_weight).to(device))

Epochs:   0%|          | 0/100 [00:00<?, ?it/s]

Epoch 1/100:
Train Loss: 0.4675, Train Acc: 0.4662
Val Loss: 0.4210, Val Acc: 0.7292
New best model saved!
Epoch 2/100:
Train Loss: 0.4887, Train Acc: 0.6248
Val Loss: 0.4204, Val Acc: 0.7292
New best model saved!
Epoch 3/100:
Train Loss: 0.4995, Train Acc: 0.4990
Val Loss: 0.3886, Val Acc: 0.3646
New best model saved!
Epoch 4/100:
Train Loss: 0.4679, Train Acc: 0.4313
Val Loss: 0.3970, Val Acc: 0.2708
Epoch 5/100:
Train Loss: 0.4283, Train Acc: 0.4101
Val Loss: 0.3970, Val Acc: 0.2917
Epoch 6/100:
Train Loss: 0.4481, Train Acc: 0.4139
Val Loss: 0.3952, Val Acc: 0.4271
Epoch 7/100:
Train Loss: 0.4122, Train Acc: 0.5184
Val Loss: 0.4061, Val Acc: 0.7188
Epoch 8/100:
Train Loss: 0.4639, Train Acc: 0.5648
Val Loss: 0.4012, Val Acc: 0.7188
Epoch 9/100:
Train Loss: 0.4310, Train Acc: 0.5029
Val Loss: 0.3880, Val Acc: 0.3542
New best model saved!
Epoch 10/100:
Train Loss: 0.4856, Train Acc: 0.5397
Val Loss: 0.3889, Val Acc: 0.6250
Epoch 11/100:
Train Loss: 0.4052, Train Acc: 0.4990
Val Loss: 0.3879, Val Acc: 0.5833
New best model saved!
Epoch 12/100:
Train Loss: 0.4998, Train Acc: 0.5319
Val Loss: 0.3878, Val Acc: 0.5938
New best model saved!
Epoch 13/100:
Train Loss: 0.4103, Train Acc: 0.4720
Val Loss: 0.3926, Val Acc: 0.2708
Epoch 14/100:
Train Loss: 0.4307, Train Acc: 0.4101
Val Loss: 0.3875, Val Acc: 0.3438
New best model saved!
Epoch 15/100:
Train Loss: 0.4421, Train Acc: 0.4275
Val Loss: 0.3877, Val Acc: 0.3333
Epoch 16/100:
Train Loss: 0.4337, Train Acc: 0.4662
Val Loss: 0.3890, Val Acc: 0.6146
Epoch 17/100:
Train Loss: 0.3973, Train Acc: 0.5203
Val Loss: 0.3973, Val Acc: 0.6771
Epoch 18/100:
Train Loss: 0.4131, Train Acc: 0.5377
Val Loss: 0.3974, Val Acc: 0.5833
Epoch 19/100:
Train Loss: 0.4376, Train Acc: 0.5280
Val Loss: 0.3918, Val Acc: 0.3125
Epoch 20/100:
Train Loss: 0.4331, Train Acc: 0.3926
Val Loss: 0.3979, Val Acc: 0.2708
Epoch 21/100:
Train Loss: 0.4680, Train Acc: 0.3752
Val Loss: 0.3980, Val Acc: 0.2708
Epoch 22/100:
Train Loss: 0.4043, Train Acc: 0.4371
Val Loss: 0.3892, Val Acc: 0.3438
Epoch 23/100:
Train Loss: 0.4300, Train Acc: 0.4932
Val Loss: 0.3892, Val Acc: 0.6042
Epoch 24/100:
Train Loss: 0.4390, Train Acc: 0.4874
Val Loss: 0.3841, Val Acc: 0.4271
New best model saved!
Epoch 25/100:
Train Loss: 0.3939, Train Acc: 0.4565
Val Loss: 0.3813, Val Acc: 0.5000
New best model saved!
Epoch 26/100:
Train Loss: 0.3985, Train Acc: 0.4623
Val Loss: 0.3800, Val Acc: 0.6562
New best model saved!
Epoch 27/100:
Train Loss: 0.4249, Train Acc: 0.5145
Val Loss: 0.3803, Val Acc: 0.6875
Epoch 28/100:
Train Loss: 0.4120, Train Acc: 0.4584
Val Loss: 0.3825, Val Acc: 0.5729
Epoch 29/100:
Train Loss: 0.3873, Train Acc: 0.4584
Val Loss: 0.3845, Val Acc: 0.5521
Epoch 30/100:
Train Loss: 0.3956, Train Acc: 0.4971
Val Loss: 0.3851, Val Acc: 0.6875
Epoch 31/100:
Train Loss: 0.3965, Train Acc: 0.5996
Val Loss: 0.3851, Val Acc: 0.7188
Epoch 32/100:
Train Loss: 0.4269, Train Acc: 0.5455
Val Loss: 0.3856, Val Acc: 0.6979
Epoch 33/100:
Train Loss: 0.4118, Train Acc: 0.5377
Val Loss: 0.3847, Val Acc: 0.6146
Epoch 34/100:
Train Loss: 0.4028, Train Acc: 0.5377
Val Loss: 0.3839, Val Acc: 0.5625
Epoch 35/100:
Train Loss: 0.4141, Train Acc: 0.5010
Val Loss: 0.3822, Val Acc: 0.6562
Epoch 36/100:
Train Loss: 0.4046, Train Acc: 0.5106
Val Loss: 0.3816, Val Acc: 0.6354
Early stopping triggered after 36 epochs!
Loaded best model from ../results/models/openface/5.pth
Running Experiment on Fold 6
Participant 407 is missing at least one modality (OpenFace)

  0%|          | 0/29 [00:00<?, ?it/s]

  0%|          | 0/676 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/83 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/114 [00:00<?, ?it/s]

/home/ammar/MultimodalEngagement/Modeling/notebooks/../src/models/multimodal_fusion.py:73: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  criterion = nn.BCEWithLogitsLoss(pos_weight=torch.tensor(pos_weight).to(device))

Epochs:   0%|          | 0/100 [00:00<?, ?it/s]

Epoch 1/100:
Train Loss: 0.3938, Train Acc: 0.5533
Val Loss: 0.4131, Val Acc: 0.3253
New best model saved!
Epoch 2/100:
Train Loss: 0.3796, Train Acc: 0.4985
Val Loss: 0.4125, Val Acc: 0.3494
New best model saved!
Epoch 3/100:
Train Loss: 0.3828, Train Acc: 0.5429
Val Loss: 0.4123, Val Acc: 0.3614
New best model saved!
Epoch 4/100:
Train Loss: 0.3656, Train Acc: 0.5562
Val Loss: 0.4136, Val Acc: 0.5904
Epoch 5/100:
Train Loss: 0.3698, Train Acc: 0.6124
Val Loss: 0.4227, Val Acc: 0.6747
Epoch 6/100:
Train Loss: 0.3613, Train Acc: 0.6509
Val Loss: 0.4135, Val Acc: 0.6024
Epoch 7/100:
Train Loss: 0.3730, Train Acc: 0.5503
Val Loss: 0.4083, Val Acc: 0.3976
New best model saved!
Epoch 8/100:
Train Loss: 0.3655, Train Acc: 0.5533
Val Loss: 0.4049, Val Acc: 0.3373
New best model saved!
Epoch 9/100:
Train Loss: 0.3604, Train Acc: 0.6080
Val Loss: 0.4123, Val Acc: 0.6024
Epoch 10/100:
Train Loss: 0.3677, Train Acc: 0.6036
Val Loss: 0.4065, Val Acc: 0.3976
Epoch 11/100:
Train Loss: 0.3663, Train Acc: 0.6228
Val Loss: 0.4052, Val Acc: 0.4096
Epoch 12/100:
Train Loss: 0.3595, Train Acc: 0.5754
Val Loss: 0.4031, Val Acc: 0.4458
New best model saved!
Epoch 13/100:
Train Loss: 0.3561, Train Acc: 0.6627
Val Loss: 0.4052, Val Acc: 0.6506
Epoch 14/100:
Train Loss: 0.3545, Train Acc: 0.6820
Val Loss: 0.4065, Val Acc: 0.6747
Epoch 15/100:
Train Loss: 0.3559, Train Acc: 0.6716
Val Loss: 0.4114, Val Acc: 0.6747
Epoch 16/100:
Train Loss: 0.3555, Train Acc: 0.6553
Val Loss: 0.4124, Val Acc: 0.6506
Epoch 17/100:
Train Loss: 0.3629, Train Acc: 0.6257
Val Loss: 0.4070, Val Acc: 0.6386
Epoch 18/100:
Train Loss: 0.3610, Train Acc: 0.6450
Val Loss: 0.4043, Val Acc: 0.5783
Epoch 19/100:
Train Loss: 0.3602, Train Acc: 0.6805
Val Loss: 0.4076, Val Acc: 0.6867
Epoch 20/100:
Train Loss: 0.3531, Train Acc: 0.6760
Val Loss: 0.4026, Val Acc: 0.4217
New best model saved!
Epoch 21/100:
Train Loss: 0.3627, Train Acc: 0.6376
Val Loss: 0.4026, Val Acc: 0.4217
New best model saved!
Epoch 22/100:
Train Loss: 0.3623, Train Acc: 0.6553
Val Loss: 0.4047, Val Acc: 0.4458
Epoch 23/100:
Train Loss: 0.3572, Train Acc: 0.6553
Val Loss: 0.4074, Val Acc: 0.6265
Epoch 24/100:
Train Loss: 0.3600, Train Acc: 0.6953
Val Loss: 0.4102, Val Acc: 0.6145
Epoch 25/100:
Train Loss: 0.3613, Train Acc: 0.6716
Val Loss: 0.4038, Val Acc: 0.5663
Epoch 26/100:
Train Loss: 0.3632, Train Acc: 0.6775
Val Loss: 0.4044, Val Acc: 0.6627
Epoch 27/100:
Train Loss: 0.3597, Train Acc: 0.7189
Val Loss: 0.4023, Val Acc: 0.5904
New best model saved!
Epoch 28/100:
Train Loss: 0.3575, Train Acc: 0.6494
Val Loss: 0.4009, Val Acc: 0.5181
New best model saved!
Epoch 29/100:
Train Loss: 0.3561, Train Acc: 0.6109
Val Loss: 0.4007, Val Acc: 0.5542
New best model saved!
Epoch 30/100:
Train Loss: 0.3569, Train Acc: 0.6834
Val Loss: 0.4062, Val Acc: 0.6988
Epoch 31/100:
Train Loss: 0.3579, Train Acc: 0.6923
Val Loss: 0.4043, Val Acc: 0.6867
Epoch 32/100:
Train Loss: 0.3559, Train Acc: 0.6612
Val Loss: 0.3972, Val Acc: 0.3855
New best model saved!
Epoch 33/100:
Train Loss: 0.3554, Train Acc: 0.6331
Val Loss: 0.4036, Val Acc: 0.5542
Epoch 34/100:
Train Loss: 0.3571, Train Acc: 0.7263
Val Loss: 0.4140, Val Acc: 0.6867
Epoch 35/100:
Train Loss: 0.3588, Train Acc: 0.6834
Val Loss: 0.3993, Val Acc: 0.5060
Epoch 36/100:
Train Loss: 0.3577, Train Acc: 0.6287
Val Loss: 0.4000, Val Acc: 0.6145
Epoch 37/100:
Train Loss: 0.3555, Train Acc: 0.6361
Val Loss: 0.3982, Val Acc: 0.6024
Epoch 38/100:
Train Loss: 0.3547, Train Acc: 0.6908
Val Loss: 0.4017, Val Acc: 0.6506
Epoch 39/100:
Train Loss: 0.3594, Train Acc: 0.6953
Val Loss: 0.4078, Val Acc: 0.6988
Epoch 40/100:
Train Loss: 0.3582, Train Acc: 0.6760
Val Loss: 0.4023, Val Acc: 0.6988
Epoch 41/100:
Train Loss: 0.3572, Train Acc: 0.6627
Val Loss: 0.4013, Val Acc: 0.4819
Epoch 42/100:
Train Loss: 0.3597, Train Acc: 0.6657
Val Loss: 0.4012, Val Acc: 0.5060
Early stopping triggered after 42 epochs!
Loaded best model from ../results/models/openface/6.pth
Accuracy: 0.611248289946772 ± 0.15014562267302364
ROC-AUC: 0.5064925600980739 ± 0.10154344247132223

In [6]:
read_reports("../results/tables/openface/")

Accuracy: 0.611248289946772 ± 0.15014562267302364
ROC-AUC: 0.5064925600980739 ± 0.10154344247132223

                     Low           High            Avg.
Metric
precision    0.19 ± 0.16    0.69 ± 0.11     0.44 ± 0.06
recall        0.18 ± 0.3     0.76 ± 0.3     0.47 ± 0.04
f1-score     0.14 ± 0.17     0.7 ± 0.21     0.42 ± 0.02
support    36.14 ± 11.95  88.57 ± 20.45  124.71 ± 22.19

# EEG Only

In [9]:
run_experiment(dataset_root="../../Dataset/", modalities=["EEG"]);

Running Experiment on Fold 0

  0%|          | 0/25 [00:00<?, ?it/s]

  0%|          | 0/547 [00:00<?, ?it/s]

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 70 and the array at index 330 has size 0

In [ ]:
read_reports("../results/tables/eeg/")